config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :candidates
  end
  
  apipie
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "/", to: "welcome#index" #首頁標準寫法
  root "welcome#index" #另一種首頁寫法


  resources :candidates do

	  member do
	  		put :vote
	  end

  end
 
 end

  #加上resources這一行，底下的一堆routes就不用自己打了
  # resources :candidates, only: [index:, show:] 只顯示 index 跟 show
  # resources :candidates, except: [index:, show:] index 跟 show 不要，其他都要
  # get "/candidates/new", to: "candidates#new"
  # post "candidates", to: "candidates#create"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	has_many :votes
  validates :name, presence: true, uniqueness: true
  validates :party, presence: true

  def display_gender
    if gender == "1"
      "#{name} 先生"
    elsif gender == "2"
      "#{name} 女士"
    else
      name
    end
  end
  
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote] #每個方法執行前就先執行這個方法
skip_before_filter :verify_authenticity_token

	def index
		# render json:  Candidate.all
		@candidates = Candidate.all
		@text = "我是XXX，我當選之後，一定會。。。。。。"
	end

	def new
		@candidate = Candidate.new
	end

	def create
		#確認只有這幾個資料可以進資料庫
		# clean_params = params.require(:candidate).permit(:name, :gender, :age, :party) 
		
		@candidate = Candidate.new(candidate_params)
		
		if @candidate.save
			flash[:notice] = "新增成功"
			redirect_to candidates_path
		else
			render :new #是 new.html.erb，而不是 new 的方法
		end

	end

	def edit
		@candidate = Candidate.find_by(id: params[:id])

		if not @candidate #if not 也可寫成 unless
			# flash[:notice] = "查無此資料" 可以把這行寫成這方式
			redirect_to candidates_path, notice: "查無此資料"
			#上面也可以全部寫成一行 redirect_to candidates_path, notice: "查無此資料" unless @candidate
		end
	end

	def update
			# @candidate = Candidate.find_by(id: params[:id]) 底下加  private 的 find_candidate就不用寫這行
			# redirect_to candidates_path, notice: "查無此資料" unless @candidate 底下加  private 的 find_candidate就不用寫這行
		# find_candidate 有加 before_action 就可以不用寫這行


		if @candidate.update_attributes(candidate_params)
			redirect_to candidates_path, notice: "#{@candidate.name}更新成功!"
		else
			  :edit #是指 edit.html.erb
		end

	end

	def destroy
			# @candidate = Candidate.find_by(id: params[:id]) 底下加  private 的 find_candidate就不用寫這行
			# redirect_to candidates_path, notice: "查無此資料" unless @candidate 底下加  private 的 find_candidate就不用寫這行
		# find_candidate 有加 before_action 就可以不用寫這行

		@candidate.destroy
		redirect_to candidates_path, notice: "刪除成功！"
	end

	# api :GET, '/age/:id'
	# param :id, :number
	def show
			# @candidate = Candidate.find_by(id: params[:id]) 底下加  private 的 find_candidate就不用寫這行
			# redirect_to candidates_path, notice: "查無此資料" unless @candidate 底下加  private 的 find_candidate就不用寫這行
		# find_candidate 有加 before_action 就可以不用寫這行
	end

	def vote
		@candidate.votes.create(ip_address: request.remote_ip)
		
		#寄信
		VoteMailer.notify(@candidate).deliver_later #deliver_now 是指馬上寄

		redirect_to candidates_path, notice:"投票成功！"

	end

	private
	def find_candidate
		@candidate = Candidate.find_by(id: params[:id])
		redirect_to candidates_path, notice: "查無此資料" unless @candidate
	end

	def candidate_params
		params.require(:candidate).permit(:name, :gender, :age, :party)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end


def show_gender(candidate)

	if  candidate.gender =="1"
		"男"
	elsif candidate.gender =="2"
		"女"
	else
		"不知道"
	end

end

def candidate_name(candidate)
		if  candidate.gender =="1"
		"#{candidate.name}先生"
	elsif candidate.gender =="2"
		"#{candidate.name}女士"
	else
		candidate.name
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/_ad.html.erb
<div style="background-color: red; color: white">
我是廣告!
<hr />
<%= text %>
</div>

app/views/candidates/_candidate.html.erb
<li>
		<!-- <%= link_to candidate_name(candidate), candidate %> |  -->
		<%= link_to candidate.display_gender, candidate %> | 
		
		<%= candidate.votes.size %>票 | 
		<%= link_to'我要投給這個人', vote_candidate_path(candidate), method: :put %> | 
		<%= link_to'更新', edit_candidate_path(candidate) %> | 
		<%= link_to'刪除', candidate, method: :delete, data: {confirm: "確定刪除嗎？" } %>
</li>

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
  <% candidate.errors.full_messages.each do |message| %>
    - <%= message %> <br />
  <% end %>
<% end %>

<%= form_for(candidate) do |f| %>
  姓名：<%= f.text_field :name %><br />
  政黨：<%= f.text_field :party %><br />
  性別：<%= f.text_field :gender %><br />
  年紀：<%= f.number_field :age %><br />

  <%= f.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>更新候選人</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= render  'ad', text: @text %>

<!-- 
<a href="<%= new_candidate_path %>">新增</a> 建議用下面link_to方式-->
<%= link_to '新增', new_candidate_path %>


<ul>
	<!-- collecition 作迴圈這件事，前面要完整的 render partial -->
	<%= render partial: "candidate", collection: @candidates %> 
</ul>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<h1><%= candidate_name(@candidate) %><br />
性別：<%= @candidate.gender %><br />
年紀：<%= @candidate.age %><br />
政黨：<%= @candidate.party %><br />

<%= link_to '回上一頁', :back %><!-- <% link_to '回上一頁', :back %> 這樣也可以 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>hihihihh</h1>